name: Main Code Push
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Printing
        run: echo "First Printing...."
      - name: Printing
        run: echo "First Printing...."
